# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 17:15
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'category',
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_date', models.DateTimeField(blank=True, null=True)),
                ('comments_text', models.TextField(verbose_name='Комментарии:')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('post_slug', models.SlugField(max_length=200)),
                ('post_photo', models.ImageField(blank=True, null=True, upload_to='blog_titels/')),
                ('post_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание')),
                ('available', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('post_created', models.DateTimeField(auto_now_add=True)),
                ('post_updated', models.DateTimeField(auto_now=True)),
                ('post_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='blog.Category', verbose_name='Категория')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.AddField(
            model_name='comments',
            name='comments_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post'),
        ),
        migrations.AddField(
            model_name='comments',
            name='comments_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterIndexTogether(
            name='post',
            index_together=set([('id', 'post_slug')]),
        ),
    ]
