# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 17:35
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='available',
            new_name='post_available',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Описание'),
        ),
    ]
