# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170217_0852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comments_post',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='comments_user',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-post_posted'], 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='category_slug',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_created',
            new_name='post_posted',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_available',
            field=models.BooleanField(default=True, verbose_name='Опубликованно'),
        ),
        migrations.AlterIndexTogether(
            name='post',
            index_together=set([]),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_updated',
        ),
    ]
