# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 05:50
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170225_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='blog.Category', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_short_description',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Короткое описание'),
        ),
    ]
